### PR TITLE
Fix issue where ENABLED is not defined

### PR DESCRIPTION
**Pull request by rchrd2**

### CODE REVIEW

**Comment by skoczen** [comment]
So, the code works as-is for lots of people, including me, which suggests that this may not be an appropriate fix.

Two things pop to mind for me, in a quick look  (I won't have time to really dig in until later in the week.)

1. That should actually be `settings.ENABLED`, and was introduced as a regression at some point, or 
2. There's something odd with your setup.  

Note that there are tests that cover this, which are passing, which means that if there's a bug, the tests are also busted and should be fixed!

**Comment by rchrd2** [comment]
Yes. On second though, I'd hold off on merging this pull request. I think the change I made just disabled prerendering altogether.

It seems the changes in this commit have caused this issue (https://github.com/skoczen/django-seo-js/commit/84c03ecaf83f5008ee6a6ad6427ffe75652c69df#diff-8c46a2eec06f6c9d6077ac71067e355b). 

I was able to successfully install the library by using an older version (`pip install https://github.com/skoczen/django-seo-js/archive/12cf78870db4aa7203ef1be3b5b00e0a86bb5499.zip`)

**Comment by skoczen** [comment]
Yep, I'm holding off, don't worry.  Yep, that looks like `settings.ENABLED`.  If you've got time to test that out, I'd be grateful.

**Comment by rchrd2** [comment]
I updated my PR to change from request.ENABLED to settings.ENABLED, and now my project loads for me without errors. I pushed to a test server and it seems to be working!

**Comment by cdelguercio** [comment]
Any reason that this hasn't been pulled in yet? I'd be glad to help test/troubleshoot any blockers.

**Comment by skoczen** [comment]
Hey @cdelguercio ,

Just time, been a bit of a crazy couple of weeks at my company and side projects.  All of my open-source projects are a bit behind at the moment.  It's on my list for this week.  Thanks much for your patience!

-Steven

**Comment by cdelguercio** [comment]
No problem Steven! Thanks so much for contributing to open-source!

**Comment by skoczen** [comment]
Finally getting this merged and released @rchrd2, I'm listing you in `AUTHORS` as 

```
rchrd2 - https://github.com/rchrd2
```

If you'd like different attribution, please toss it on this issue!

**Comment by skoczen** [comment]
This is now released in `0.3.1`!

**Pull request merged**
