### PR TITLE
Add support for sending User-Agent string to prerenderer.

### PR DESCRIPTION
**Pull request by zekzekus**
Makes changes to argument signature of the BackendBase method get_response_for_url()

Whole credit goes to @jdotjdot . 

I just removed one redundant commit (it already handled on master branch at the moment) and fix the conflict on AUTHORS file. 

Now i am open to suggestions to make this PR better. For example i think it is a better idea to pass only user agent to backend not whole django request. Also if you can clarify how to setup development environment (to run tests etc.) it would be great to make a better contribution.

### CODE REVIEW

**Comment by zekzekus** [comment]
I just fixed broken tests. Actual tests for added functionality will follow.

**Comment by pcraciunoiu** [comment]
> I just fixed broken tests. Actual tests for added functionality will follow.

Just saw this!

**Comment by zekzekus** [comment]
It seems I won't able to work on the tests for a while. So it's up to you merge this or not. For your information I did push this to production via my fork and according to our SEO agency it worked like a charm.

**Comment by pcraciunoiu** [comment]
Alright! Better for people to benefit than to hold this off. Thanks!

**Comment by pcraciunoiu** [comment]
Uploaded the release 0.3.3 to pypi.

On a separate note, are you running python 3? I assume no, but in case you do, an upgrade to support it would be great.

**Pull request merged**
